name: Tests

on:
  push:
    branches: 
      - main
      - develop
      - 'feature/**'
  pull_request:
    branches: 
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Copy package.json on root
      run: cp ./src/package.json ./package.json && cp ./src/package-lock.json ./package-lock.json
    - run: cd ./src/ && npm ci
    - run: cd ./src/ && npm test